@apiURL=http://localhost:8080

### Get rooms
GET {{apiURL}}/rooms

### Get BOOKINGS
GET {{apiURL}}/bookings

### Create booking
POST {{apiURL}}/bookings
Content-Type: application/json

{
    "room_id": 1,
}